In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from PIL import Image
import rampy
from BaselineRemoval import BaselineRemoval
%matplotlib inline
%config InlineBackend.figure_fornat = 'retina'
pd.set_option('display.max_rows',5000)
pd.set_option('display.max_columns',5000)

### Data normal

In [2]:
data = pd.read_csv('all_DataDtyrosine.csv')
data1 = pd.read_csv('all_DataL-tyrosine.csv')

In [3]:
data.drop('Unnamed: 0',axis=1,inplace=True)

In [4]:
data

NumberWave  Intenseness
0        399.45391      1.42139
1        399.21284      1.42504
2        398.97177      1.42339
3        398.73070      1.41679
4        398.48963      1.40918
...            ...          ...
192323     0.96428     -0.36698
192324     0.72321     -0.39711
192325     0.48214     -0.45737
192326     0.24107     -0.43889
192327    -0.00000     -0.04909

[192328 rows x 2 columns]

In [5]:
data1.drop('Unnamed: 0',axis=1,inplace=True)

In [6]:
data1

NumberWave  Intenseness
0        399.45391      1.40377
1        399.21284      1.39091
2        398.97177      1.39132
3        398.73070      1.40100
4        398.48963      1.40765
...            ...          ...
200613     0.96428     -0.39889
200614     0.72321     -0.42643
200615     0.48214     -0.49654
200616     0.24107     -0.46704
200617    -0.00000     -0.09735

[200618 rows x 2 columns]

In [7]:
data_all = pd.concat([data,data1])
data_all

NumberWave  Intenseness
0        399.45391      1.42139
1        399.21284      1.42504
2        398.97177      1.42339
3        398.73070      1.41679
4        398.48963      1.40918
...            ...          ...
200613     0.96428     -0.39889
200614     0.72321     -0.42643
200615     0.48214     -0.49654
200616     0.24107     -0.46704
200617    -0.00000     -0.09735

[392946 rows x 2 columns]

In [8]:
X = data_all['Intenseness']
X.shape

(392946,)

In [76]:
from sklearn import preprocessing
from keras.utils import to_categorical
y = np.zeros((X_arrall.shape[0],1))
for i in range(0,196473,1):
    if(0<=i<=98236):
        y[i]=0
    elif(98237<=i<=196472):
        y[i]=1
encoder = preprocessing.LabelEncoder()
encoder.fit(y)
encoder_Y = encoder.transform(y)
Y_all = to_categorical(encoder_Y)

In [77]:
Y_all

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [60]:
Y_all = Y_all.reshape(-1,1)
Y_all.shape

(785892, 1)

In [9]:
y1 = []
for i in range(0,196473,1):
    y1.append(0.)
    y1.append(1.)

In [10]:
y = np.array(y1)

In [58]:
encoder = preprocessing.LabelEncoder()
encoder.fit(y)
encoder_Y = encoder.transform(y)
Y_all = to_categorical(encoder_Y)

In [59]:
Y_all.shape

(392946, 2)

In [11]:
X = np.array(X)
X

array([ 1.42139,  1.42504,  1.42339, ..., -0.49654, -0.46704, -0.09735])

In [12]:
X.shape,y.shape

((392946,), (392946,))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [14]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(314356,) (78590,) (314356,) (78590,)


In [15]:
X_train=X_train.reshape(-1,1)
y_train=y_train.reshape(-1,1)

In [16]:
X_train.shape,y_train.shape

((314356, 1), (314356, 1))

In [17]:
model_Logistic = LogisticRegression()
model_KN = KNeighborsClassifier()
model_Tree = DecisionTreeClassifier()
model_SVC = SVC()
model_GN= GaussianNB()
model_Random = RandomForestClassifier()
model_SGD = SGDClassifier()

In [18]:
model_Logistic.fit(X_train,y_train)
model_KN.fit(X_train,y_train)
model_Tree.fit(X_train,y_train)
model_SVC.fit(X_train,y_train)
model_GN.fit(X_train,y_train)
model_Random.fit(X_train,y_train)
model_SGD.fit(X_train,y_train)

SGDClassifier()

In [90]:
model_KN = KNeighborsClassifier()
model_Tree = DecisionTreeClassifier()
model_Random = RandomForestClassifier()
model_KN.fit(X_train,y_train)
model_Tree.fit(X_train,y_train)
model_Random.fit(X_train,y_train)
y_pred_KN = model_KN.predict(X_test)
y_pred_Tree = model_Tree.predict(X_test)
y_pred_Random =model_Random.predict(X_test)
accuracyKN =accuracy_score(y_test,y_pred_KN)
accuracyTree = accuracy_score(y_test,y_pred_Tree)
accuracyRandom= accuracy_score(y_test,y_pred_Random)
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom))

accuracy_KNeighborsClassifier : 70.00%
accuracy_DecisionTreeClassifier : 58.26%
accuracy_RandomForestClassifier :  65.81%


In [20]:
X_test=X_test.reshape(-1,1)

In [21]:
y_pred_Logistic = model_Logistic.predict(X_test)
y_pred_KN = model_KN.predict(X_test)
y_pred_Tree = model_Tree.predict(X_test)
y_pred_SVC = model_SVC.predict(X_test)
y_pred_GN =model_GN.predict(X_test)
y_pred_Random =model_Random.predict(X_test)
y_pred_SGD = model_SGD.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
accuracyLG = accuracy_score(y_test,y_pred_Logistic)
accuracyKN =accuracy_score(y_test,y_pred_KN)
accuracyTree = accuracy_score(y_test,y_pred_Tree)
accuracySVC = accuracy_score(y_test,y_pred_SVC)
accuracyGN = accuracy_score(y_test,y_pred_GN)
accuracyRandom= accuracy_score(y_test,y_pred_Random)
accuracySGD = accuracy_score(y_test,y_pred_SGD)

In [24]:
print('accuracy_Logistic :',"{:.2%}".format(accuracyLG))
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree))
print('accuracy_SVC :',"{:.2%}".format(accuracySVC))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyGN))
print('accuracy_GaussianNB :',"{:.2%}".format(accuracyRandom))
print('accuracy_SGDClassifier : ',"{:.2%}".format(accuracySGD))

accuracy_Logistic : 49.83%
accuracy_KNeighborsClassifier : 50.12%
accuracy_DecisionTreeClassifier : 50.18%
accuracy_SVC : 49.71%
accuracy_RandomForestClassifier :  49.78%
accuracy_GaussianNB : 50.30%
accuracy_SGDClassifier :  49.86%


In [19]:
from sklearn.metrics import mean_squared_error,r2_score
## MSE
MSE_Logistic = mean_squared_error(y_test,y_pred_Logistic)
MSE_KN = mean_squared_error(y_test,y_pred_KN)
MSE_Tree = mean_squared_error(y_test,y_pred_Tree)
MSE_SVC = mean_squared_error(y_test,y_pred_SVC)
MSE_GN = mean_squared_error(y_test,y_pred_GN)
MSE_Random = mean_squared_error(y_test,y_pred_Random)
MSE_SGD = mean_squared_error(y_test,y_pred_SGD)

#R-Square
R2_Logistic = r2_score(y_test,y_pred_Logistic)
R2_KN = r2_score(y_test,y_pred_KN)
R2_Tree = r2_score(y_test,y_pred_Tree)
R2_SVC = r2_score(y_test,y_pred_SVC)
R2_GN = r2_score(y_test,y_pred_GN)
R2_Random = r2_score(y_test,y_pred_Random)
R2_SGD = r2_score(y_test,y_pred_SGD)

In [22]:
print('MSE_Logistic :',MSE_Logistic)
print('MSE_KNeighborsClassifier :',MSE_KN)
print('MSE_DecisionTreeClassifier :',MSE_Tree)
print('MSE_SVC :',MSE_SVC)
print('MSE_RandomForestClassifier : ',MSE_Random)
print('MSE_GaussianNB :',MSE_GN)
print('MSE_SGDClassifier :',MSE_SGD)

MSE_Logistic : 0.5016923272681003
MSE_KNeighborsClassifier : 0.4997200661661789
MSE_DecisionTreeClassifier : 0.4981804300801629
MSE_SVC : 0.5029011324596004
MSE_RandomForestClassifier :  0.4968698307672732
MSE_GaussianNB : 0.5021631250795267


In [23]:
print('R2_Logistic : ',R2_Logistic)
print('R2_KNeighborsClassifier :',R2_KN)
print('R2_DecisionTreeClassifier :',R2_Tree)
print('R2_SVC : ',R2_SVC)
print('R2_RandomForestClassifier : ',R2_Random)
print('R2_GaussianNB : ',R2_GN)
print('R2_SGDClassifier :',R2_SGD)

R2_Logistic :  -1.0067861993280163
R2_KNeighborsClassifier : -0.9988970885210811
R2_DecisionTreeClassifier : -0.992738492342764
R2_SVC :  -1.0116214607903316
R2_RandomForestClassifier :  -0.9874960509678328
R2_GaussianNB :  -1.0086694064238655


## Crop Spec data 0.3THz to 3THz

In [38]:
dataCropD = pd.read_csv('CropSpec_D-Tyrosine.csv')
dataCropL = pd.read_csv('CropSpec_L-Tyrosine.csv')

In [39]:
dataCropD.drop('Unnamed: 0',axis=1,inplace=True)

In [40]:
dataCropL.drop('Unnamed: 0',axis=1,inplace=True)

In [39]:
dataCropD.rename(columns = { i: "Intenseness" for i in  dataCropD.columns if i.startswith("Inten") },inplace=True)

In [36]:
dataCropL.rename(columns = { i: "Intenseness" for i in  dataCropD.columns if i.startswith("Inten") },inplace=True)

In [41]:
dataCropL.head()

Frequency  Intensity0  Intensity1  Intensity2  Intensity3  Intensity4  \
0   0.300196     0.19626     0.20509     0.19930     0.19238     0.19701   
1   0.301187     0.19748     0.20446     0.19670     0.19027     0.19455   
2   0.302184     0.19578     0.20300     0.19284     0.18777     0.19103   
3   0.303188     0.19263     0.20136     0.18961     0.18593     0.18743   
4   0.304199     0.19048     0.19989     0.18877     0.18542     0.18406   

   Intensity5  Intensity6  Intensity7  Intensity8  Intensity9  Intensity10  \
0     0.20302     0.19990     0.18343     0.19653     0.20473      0.18725   
1     0.20130     0.19675     0.18150     0.19368     0.20073      0.18587   
2     0.19762     0.19449     0.17887     0.19190     0.19367      0.18312   
3     0.19332     0.19390     0.17672     0.19109     0.18853      0.18050   
4     0.18922     0.19330     0.17672     0.19189     0.18832      0.18005   

   Intensity11  Intensity12  Intensity13  Intensity14  Intensity15  \
0      0.09315      0.09655      0.08758      0.14316      0.26793   
1      0.09048      0.09587      0.08423      0.14267      0.27067   
2      0.08866      0.09547      0.08354      0.14243      0.27451   
3      0.08537      0.09601      0.08394      0.14387      0.27770   
4      0.08106      0.09556      0.08411      0.14687      0.27638   

   Intensity16  Intensity17  Intensity18  Intensity19  Intensity20  \
0      0.23694      0.16764      0.16325      0.18156      0.22171   
1      0.21033      0.17427      0.16263      0.17551      0.19091   
2      0.16897      0.18124      0.16679      0.16687      0.16632   
3      0.13785      0.18354      0.17457      0.15721      0.15706   
4      0.12740      0.17722      0.18327      0.14934      0.16608   

   Intensity21  Intensity22  Intensity23  Intensity24  Intensity25  \
0      0.19158      0.18327      0.20755      0.22132      0.35630   
1      0.18961      0.18329      0.19928      0.21330      0.35158   
2      0.18522      0.18751      0.18569      0.22105      0.34419   
3      0.18462      0.19931      0.17787      0.23546      0.33936   
4      0.18808      0.21811      0.18091      0.23503      0.33113   

   Intensity26  Intensity27  Intensity28  Intensity29  Intensity30  \
0      0.27504      0.18991      0.16127      0.17719      0.19276   
1      0.27444      0.18442      0.14934      0.18010      0.17982   
2      0.26313      0.17741      0.14608      0.17578      0.16440   
3      0.25388      0.17678      0.15602      0.17002      0.14947   
4      0.25162      0.18293      0.17284      0.17077      0.13838   

   Intensity31  Intensity32  Intensity33  Intensity34  Intensity35  \
0      0.15386      0.17916      0.15925      0.16732      0.16440   
1      0.15160      0.17990      0.16214      0.16737      0.16057   
2      0.15081      0.17333      0.16508      0.16746      0.15849   
3      0.15346      0.16173      0.16550      0.16739      0.15505   
4      0.15822      0.15118      0.16179      0.16680      0.15147   

   Intensity36  Intensity37  Intensity38  Intensity39  Intensity40  \
0      0.16228      0.16729      0.16029      0.17236      0.16126   
1      0.16158      0.16037      0.15970      0.16837      0.15439   
2      0.15550      0.15636      0.15629      0.15910      0.15257   
3      0.14922      0.15854      0.15003      0.14915      0.15621   
4      0.14751      0.16624      0.14377      0.14389      0.16026   

   Intensity41  Intensity42  Intensity43  Intensity44  Intensity45  \
0      0.16773      0.17803      0.17509      0.14996      0.15597   
1      0.17400      0.16812      0.17003      0.14940      0.15444   
2      0.17581      0.16327      0.16360      0.14908      0.15180   
3      0.17004      0.16470      0.16241      0.14867      0.14927   
4      0.16071      0.17191      0.16992      0.14761      0.14871   

   Intensity46  Intensity47  Intensity48  Intensity49  Intensity50  \
0      0.16362      0.14769      0.16305      0.15785      0

In [42]:
dataCropD.head()

Frequency  Intensity0  Intensity1  Intensity2  Intensity3  Intensity4  \
0   0.300196     0.19005     0.18486     0.18657     0.18505     0.18858   
1   0.301187     0.19094     0.18610     0.18796     0.18392     0.18586   
2   0.302184     0.19159     0.18644     0.18853     0.18279     0.18354   
3   0.303188     0.19252     0.18593     0.18937     0.18269     0.18298   
4   0.304199     0.19342     0.18509     0.19126     0.18365     0.18361   

   Intensity5  Intensity6  Intensity7  Intensity8  Intensity9  Intensity10  \
0     0.18406     0.18809     0.18496     0.18398     0.18601      0.18140   
1     0.18391     0.18709     0.18605     0.18394     0.18284      0.17878   
2     0.18337     0.18663     0.18607     0.18399     0.17809      0.17677   
3     0.18200     0.18747     0.18650     0.18578     0.17575      0.17700   
4     0.17976     0.18914     0.18888     0.18963     0.17699      0.17946   

   Intensity11  Intensity12  Intensity13  Intensity14  Intensity15  \
0      0.09461      0.25409      0.10110      0.08023      0.09090   
1      0.09430      0.25434      0.10126      0.07707      0.09165   
2      0.09370      0.26004      0.09979      0.07749      0.09541   
3      0.09399      0.26910      0.09747      0.08143      0.09973   
4      0.09563      0.27410      0.09635      0.08631      0.10219   

   Intensity16  Intensity17  Intensity18  Intensity19  Intensity20  \
0      0.10043      0.11090      0.09135      0.09709      0.09709   
1      0.10035      0.11201      0.09165      0.09462      0.09791   
2      0.10196      0.11367      0.09290      0.09266      0.09866   
3      0.10451      0.11438      0.09621      0.09349      0.09915   
4      0.10697      0.11321      0.10034      0.09714      0.09812   

   Intensity21  Intensity22  Intensity23  Intensity24  Intensity25  \
0      0.09735      0.13608      0.10478      0.09728      0.09625   
1      0.09645      0.13031      0.10561      0.09549      0.09705   
2      0.09581      0.12343      0.10513      0.09329      0.09533   
3      0.09606      0.11946      0.10452      0.09255      0.09367   
4      0.09573      0.11973      0.10486      0.09369      0.09451   

   Intensity26  Intensity27  Intensity28  Intensity29  Intensity30  \
0      0.17168      0.16139      0.16777      0.10269      0.17181   
1      0.16767      0.15915      0.16545      0.10298      0.16864   
2      0.16430      0.15750      0.16456      0.10358      0.16285   
3      0.16572      0.15882      0.16703      0.10441      0.16000   
4      0.17199      0.16325      0.17182      0.10540      0.16314   

   Intensity31  Intensity32  Intensity33  Intensity34  Intensity35  \
0      0.16475      0.16377      0.16199      0.16649      0.15464   
1      0.16543      0.16293      0.16571      0.16578      0.15156   
2      0.16667      0.16259      0.16718      0.16504      0.15638   
3      0.16845      0.16394      0.16647      0.16541      0.16712   
4      0.16927      0.16572      0.16507      0.16548      0.17847   

   Intensity36  Intensity37  Intensity38  Intensity39  Intensity40  \
0      0.16197      0.10972      0.10604      0.16010      0.15163   
1      0.16693      0.10945      0.10424      0.16083      0.15597   
2      0.17294      0.10890      0.10366      0.16190      0.15841   
3      0.17840      0.10837      0.10484      0.16366      0.15862   
4      0.18155      0.10804      0.10696      0.16578      0.15823   

   Intensity41  Intensity42  Intensity43  Intensity44  Intensity45  \
0      0.16678      0.15253      0.15702      0.15583      0.15365   
1      0.16877      0.15164      0.15660      0.15223      0.15499   
2      0.16726      0.15031      0.15637      0.14991      0.16006   
3      0.16390      0.15069      0.15764      0.15015      0.16537   
4      0.16108      0.15361      0.15986      0.15417      0.16733   

   Intensity46  Intensity47  Intensity48  Intensity49  Intensity50  \
0      0.15992      0.14900      0.16662      0.15053      0

In [43]:
df=dataCropD.iloc[:,1:116]

In [44]:
df.head()

Intensity0  Intensity1  Intensity2  Intensity3  Intensity4  Intensity5  \
0     0.19005     0.18486     0.18657     0.18505     0.18858     0.18406   
1     0.19094     0.18610     0.18796     0.18392     0.18586     0.18391   
2     0.19159     0.18644     0.18853     0.18279     0.18354     0.18337   
3     0.19252     0.18593     0.18937     0.18269     0.18298     0.18200   
4     0.19342     0.18509     0.19126     0.18365     0.18361     0.17976   

   Intensity6  Intensity7  Intensity8  Intensity9  Intensity10  Intensity11  \
0     0.18809     0.18496     0.18398     0.18601      0.18140      0.09461   
1     0.18709     0.18605     0.18394     0.18284      0.17878      0.09430   
2     0.18663     0.18607     0.18399     0.17809      0.17677      0.09370   
3     0.18747     0.18650     0.18578     0.17575      0.17700      0.09399   
4     0.18914     0.18888     0.18963     0.17699      0.17946      0.09563   

   Intensity12  Intensity13  Intensity14  Intensity15  Intensity16  \
0      0.25409      0.10110      0.08023      0.09090      0.10043   
1      0.25434      0.10126      0.07707      0.09165      0.10035   
2      0.26004      0.09979      0.07749      0.09541      0.10196   
3      0.26910      0.09747      0.08143      0.09973      0.10451   
4      0.27410      0.09635      0.08631      0.10219      0.10697   

   Intensity17  Intensity18  Intensity19  Intensity20  Intensity21  \
0      0.11090      0.09135      0.09709      0.09709      0.09735   
1      0.11201      0.09165      0.09462      0.09791      0.09645   
2      0.11367      0.09290      0.09266      0.09866      0.09581   
3      0.11438      0.09621      0.09349      0.09915      0.09606   
4      0.11321      0.10034      0.09714      0.09812      0.09573   

   Intensity22  Intensity23  Intensity24  Intensity25  Intensity26  \
0      0.13608      0.10478      0.09728      0.09625      0.17168   
1      0.13031      0.10561      0.09549      0.09705      0.16767   
2      0.12343      0.10513      0.09329      0.09533      0.16430   
3      0.11946      0.10452      0.09255      0.09367      0.16572   
4      0.11973      0.10486      0.09369      0.09451      0.17199   

   Intensity27  Intensity28  Intensity29  Intensity30  Intensity31  \
0      0.16139      0.16777      0.10269      0.17181      0.16475   
1      0.15915      0.16545      0.10298      0.16864      0.16543   
2      0.15750      0.16456      0.10358      0.16285      0.16667   
3      0.15882      0.16703      0.10441      0.16000      0.16845   
4      0.16325      0.17182      0.10540      0.16314      0.16927   

   Intensity32  Intensity33  Intensity34  Intensity35  Intensity36  \
0      0.16377      0.16199      0.16649      0.15464      0.16197   
1      0.16293      0.16571      0.16578      0.15156      0.16693   
2      0.16259      0.16718      0.16504      0.15638      0.17294   
3      0.16394      0.16647      0.16541      0.16712      0.17840   
4      0.16572      0.16507      0.16548      0.17847      0.18155   

   Intensity37  Intensity38  Intensity39  Intensity40  Intensity41  \
0      0.10972      0.10604      0.16010      0.15163      0.16678   
1      0.10945      0.10424      0.16083      0.15597      0.16877   
2      0.10890      0.10366      0.16190      0.15841      0.16726   
3      0.10837      0.10484      0.16366      0.15862      0.16390   
4      0.10804      0.10696      0.16578      0.15823      0.16108   

   Intensity42  Intensity43  Intensity44  Intensity45  Intensity46  \
0      0.15253      0.15702      0.15583      0.15365      0.15992   
1      0.15164      0.15660      0.15223      0.15499      0.16037   
2      0.15031      0.15637      0.14991      0.16006      0.16181   
3      0.15069      0.15764      0.15015      0.16537      0.16152   
4      0.15361      0.15986      0.15417      0.16733      0.15859   

   Intensity47  Intensity48  Intensity49  Intensity50  Intensity51  \
0      0.14900      0.16662      0.15053      0.

In [105]:
df.iloc[:,114]

0      0.14234
1      0.14400
2      0.14317
3      0.14119
4      0.14080
5      0.14452
6      0.15274
7      0.16279
8      0.17061
9      0.17375
10     0.17282
11     0.17088
12     0.17220
13     0.18058
14     0.19732
15     0.22009
16     0.24346
17     0.26071
18     0.26642
19     0.25923
20     0.24209
21     0.21919
22     0.19443
23     0.17193
24     0.15524
25     0.14493
26     0.13847
27     0.13272
28     0.12669
29     0.12185
30     0.12021
31     0.12220
32     0.12665
33     0.13250
34     0.14004
35     0.15046
36     0.16418
37     0.17933
38     0.19167
39     0.19712
40     0.19460
41     0.18622
42     0.17530
43     0.16461
44     0.15546
45     0.14775
46     0.14143
47     0.13737
48     0.13604
49     0.13605
50     0.13492
51     0.13141
52     0.12687
53     0.12423
54     0.12536
55     0.12930
56     0.13316
57     0.13472
58     0.13370
59     0.13094
60     0.12723
61     0.12299
62     0.11893
63     0.11713
64     0.12031
65     0.12923
66     0.1

In [45]:
df2=dataCropL.iloc[:,1:121]

In [46]:
X1 = []
for i in range(0,115,1):
    df1=df.iloc[:,i]
    X1.append(df1)

In [12]:
X1

[0      0.19005
 1      0.19094
 2      0.19159
 3      0.19252
 4      0.19342
 5      0.19346
 6      0.19263
 7      0.19196
 8      0.19229
 9      0.19376
 10     0.19646
 11     0.20080
 12     0.20782
 13     0.21924
 14     0.23638
 15     0.25802
 16     0.27924
 17     0.29322
 18     0.29581
 19     0.28836
 20     0.27522
 21     0.25979
 22     0.24366
 23     0.22767
 24     0.21279
 25     0.20013
 26     0.19043
 27     0.18339
 28     0.17750
 29     0.17115
 30     0.16437
 31     0.15911
 32     0.15768
 33     0.16069
 34     0.16679
 35     0.17403
 36     0.18137
 37     0.18899
 38     0.19688
 39     0.20382
 40     0.20857
 41     0.21125
 42     0.21258
 43     0.21285
 44     0.21231
 45     0.21142
 46     0.21010
 47     0.20741
 48     0.20193
 49     0.19285
 50     0.18121
 51     0.16966
 52     0.16030
 53     0.15352
 54     0.14933
 55     0.14917
 56     0.15559
 57     0.16916
 58     0.18609
 59     0.20032
 60     0.20764
 61     0.20671
 62     

In [47]:
X2 = []
for i in range(0,115,1):
    df4=df2.iloc[:,i]
    X2.append(df4)

In [48]:
X_arr = np.array(X1)
X_arr.shape

(115, 275)

In [50]:
X_arr

array([[ 0.19005,  0.19094,  0.19159, ..., -0.47458, -0.48173, -0.48273],
       [ 0.18486,  0.1861 ,  0.18644, ..., -0.42763, -0.44875, -0.47319],
       [ 0.18657,  0.18796,  0.18853, ..., -0.35825, -0.35837, -0.36569],
       ...,
       [ 0.13994,  0.13944,  0.13923, ..., -0.49484, -0.48063, -0.48557],
       [ 0.14442,  0.13863,  0.13334, ..., -0.34107, -0.32924, -0.33965],
       [ 0.14234,  0.144  ,  0.14317, ..., -0.38865, -0.39607, -0.41891]])

In [49]:
X_arr1 = np.array(X2)
X_arr1.shape

(115, 275)

In [51]:
X_arr1

array([[ 0.19626,  0.19748,  0.19578, ..., -0.47312, -0.45869, -0.43383],
       [ 0.20509,  0.20446,  0.203  , ..., -0.42772, -0.41536, -0.40886],
       [ 0.1993 ,  0.1967 ,  0.19284, ..., -0.40404, -0.41022, -0.40851],
       ...,
       [ 0.17859,  0.17603,  0.1742 , ..., -0.43525, -0.4284 , -0.43178],
       [ 0.1669 ,  0.16775,  0.16736, ..., -0.43741, -0.44838, -0.46773],
       [ 0.17543,  0.17462,  0.17406, ..., -0.38778, -0.39354, -0.39428]])

In [52]:
X_arrall=np.concatenate((X_arr,X_arr1))

In [53]:
X_arrall.shape

(230, 275)

In [54]:
X_arrall

array([[ 0.19005,  0.19094,  0.19159, ..., -0.47458, -0.48173, -0.48273],
       [ 0.18486,  0.1861 ,  0.18644, ..., -0.42763, -0.44875, -0.47319],
       [ 0.18657,  0.18796,  0.18853, ..., -0.35825, -0.35837, -0.36569],
       ...,
       [ 0.17859,  0.17603,  0.1742 , ..., -0.43525, -0.4284 , -0.43178],
       [ 0.1669 ,  0.16775,  0.16736, ..., -0.43741, -0.44838, -0.46773],
       [ 0.17543,  0.17462,  0.17406, ..., -0.38778, -0.39354, -0.39428]])

In [55]:
X_final=X_arrall.reshape(-1,1)

In [56]:
X_final
print(X_final.shape)

(63250, 1)


In [20]:
from sklearn import preprocessing
from keras.utils import to_categorical
y = np.zeros((X_final.shape[0],1))
for i in range(0,31625,1):
    if(0<=i<=15812):
        y[i]=0
    elif(98237<=i<=31625):
        y[i]=1
encoder = preprocessing.LabelEncoder()
encoder.fit(y)
encoder_Y = encoder.transform(y)
Y_all = to_categorical(encoder_Y)

In [58]:
Y_all

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [22]:
y1 = []
for i in range(0,31625,1):
    y1.append(0.)
    y1.append(1.)

In [23]:
y_arr = np.array(y1)

In [24]:
y_arr=y_arr.reshape(-1,1)

In [25]:
y_arr.shape

(63250, 1)

In [26]:
y_arr

array([[0.],
       [1.],
       [0.],
       ...,
       [1.],
       [0.],
       [1.]])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X_final,y_arr, test_size = 0.2, random_state = 42)

In [28]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(50600, 1) (12650, 1) (50600, 1) (12650, 1)


In [30]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=1)

In [31]:
from sklearn import preprocessing
from keras.utils import to_categorical
le = preprocessing.LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_val = le.transform(y_val)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_val = to_categorical(y_val)

In [32]:
print(y_train.shape,y_test.shape,y_val.shape)

(37950, 2) (12650, 2) (12650, 2)


In [33]:
model_Logistic1 = LogisticRegression()
model_KN1 = KNeighborsClassifier()
model_Tree1 = DecisionTreeClassifier()
model_SVC1 = SVC()
model_GN1 = GaussianNB()
model_Random1 = RandomForestClassifier()
model_SGD1 = SGDClassifier()

In [34]:
model_Logistic1.fit(X_train,y_train)
model_KN1.fit(X_train,y_train)
model_Tree1.fit(X_train,y_train)
model_SVC1.fit(X_train,y_train)
model_GN1.fit(X_train,y_train)
model_Random1.fit(X_train,y_train)
model_SGD1.fit(X_train,y_train)

ValueError: y should be a 1d array, got an array of shape (37950, 2) instead.

In [37]:
from sklearn.metrics import accuracy_score
model_KN2 = KNeighborsClassifier()
model_Tree2 = DecisionTreeClassifier()
model_Random2 = RandomForestClassifier()
model_KN2.fit(X_train,y_train)
model_Tree2.fit(X_train,y_train)
model_Random2.fit(X_train,y_train)
y_pred_KN2 = model_KN2.predict(X_test)
y_pred_Tree2 = model_Tree2.predict(X_test)
y_pred_Random2 =model_Random2.predict(X_test)
accuracyKN2 =accuracy_score(y_test,y_pred_KN2)
accuracyTree2 = accuracy_score(y_test,y_pred_Tree2)
accuracyRandom2 = accuracy_score(y_test,y_pred_Random2)
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN2))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree2))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom2))

accuracy_KNeighborsClassifier : 49.60%
accuracy_DecisionTreeClassifier : 43.45%
accuracy_RandomForestClassifier :  49.57%


In [76]:
y_pred_Logistic1 = model_Logistic1.predict(X_test)
y_pred_KN1 = model_KN1.predict(X_test)
y_pred_Tree1 = model_Tree1.predict(X_test)
y_pred_SVC1= model_SVC1.predict(X_test)
y_pred_GN1 =model_GN1.predict(X_test)
y_pred_Random1 =model_Random1.predict(X_test)
y_pred_SGD1 = model_SGD1.predict(X_test)

In [77]:
accuracyLG1 = accuracy_score(y_test,y_pred_Logistic1)
accuracyKN1 =accuracy_score(y_test,y_pred_KN1)
accuracyTree1 = accuracy_score(y_test,y_pred_Tree1)
accuracySVC1 = accuracy_score(y_test,y_pred_SVC1)
accuracyGN1 = accuracy_score(y_test,y_pred_GN1)
accuracyRandom1= accuracy_score(y_test,y_pred_Random1)
accuracySGD1 = accuracy_score(y_test,y_pred_SGD1)
print('accuracy_Logistic :',"{:.2%}".format(accuracyLG1))
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN1))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree1))
print('accuracy_SVC :',"{:.2%}".format(accuracySVC1))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyGN1))
print('accuracy_GaussianNB :',"{:.2%}".format(accuracyRandom1))
print('accuracy_SGDClassifier : ',"{:.2%}".format(accuracySGD1))

accuracy_Logistic : 48.76%
accuracy_KNeighborsClassifier : 49.82%
accuracy_DecisionTreeClassifier : 49.55%
accuracy_SVC : 48.97%
accuracy_RandomForestClassifier :  49.07%
accuracy_GaussianNB : 49.34%
accuracy_SGDClassifier :  49.81%


In [44]:
from sklearn.metrics import mean_squared_error,r2_score
## MSE
MSE_Logistic1 = mean_squared_error(y_test,y_pred_Logistic1)
MSE_KN1 = mean_squared_error(y_test,y_pred_KN1)
MSE_Tree1 = mean_squared_error(y_test,y_pred_Tree1)
MSE_SVC1 = mean_squared_error(y_test,y_pred_SVC1)
MSE_GN1 = mean_squared_error(y_test,y_pred_GN1)
MSE_Random1 = mean_squared_error(y_test,y_pred_Random1)

#R-Square
R2_Logistic1 = r2_score(y_test,y_pred_Logistic1)
R2_KN1 = r2_score(y_test,y_pred_KN1)
R2_Tree1 = r2_score(y_test,y_pred_Tree1)
R2_SVC1 = r2_score(y_test,y_pred_SVC1)
R2_GN1 = r2_score(y_test,y_pred_GN1)
R2_Random1 = r2_score(y_test,y_pred_Random1)


In [27]:
print('MSE_Logistic :',MSE_Logistic1)
print('MSE_KNeighborsClassifier :',MSE_KN1)
print('MSE_DecisionTreeClassifier :',MSE_Tree1)
print('MSE_SVC :',MSE_SVC1)
print('MSE_RandomForestClassifier : ',MSE_Random1)
print('MSE_GaussianNB :',MSE_GN1)

MSE_Logistic : 0.5124110671936759
MSE_KNeighborsClassifier : 0.5017391304347826
MSE_DecisionTreeClassifier : 0.5045059288537549
MSE_SVC : 0.5102766798418973
MSE_RandomForestClassifier :  0.5049011857707509
MSE_GaussianNB : 0.5093280632411067


In [45]:
print('MSE_Logistic :',MSE_Logistic1)
print('MSE_KNeighborsClassifier :',MSE_KN1)
print('MSE_DecisionTreeClassifier :',MSE_Tree1)
print('MSE_SVC :',MSE_SVC1)
print('MSE_RandomForestClassifier : ',MSE_Random1)
print('MSE_GaussianNB :',MSE_GN1)

MSE_Logistic : 0.5124110671936759
MSE_KNeighborsClassifier : 0.5017391304347826
MSE_DecisionTreeClassifier : 0.5045059288537549
MSE_SVC : 0.5102766798418973
MSE_RandomForestClassifier :  0.5037944664031621
MSE_GaussianNB : 0.5093280632411067


In [28]:
print('R2_Logistic : ',R2_Logistic1)
print('R2_KNeighborsClassifier :',R2_KN1)
print('R2_DecisionTreeClassifier :',R2_Tree1)
print('R2_SVC : ',R2_SVC1)
print('R2_RandomForestClassifier : ',R2_Random1)
print('R2_GaussianNB : ',R2_GN1)

R2_Logistic :  -1.0496737799271294
R2_KNeighborsClassifier : -1.0069854182655802
R2_DecisionTreeClassifier : -1.0180527712889447
R2_SVC :  -1.0411361075948196
R2_RandomForestClassifier :  -1.0196338217208538
R2_GaussianNB :  -1.0373415865582376


### Base line Data

In [91]:
Data_BLD = np.load('D_Tyrosine_Baseline.npy')

In [92]:
Data_BLD

array([[-1.18036410e-02, -5.35065208e-03, -4.19763393e-03, ...,
        -6.21412292e-02, -7.41671041e-02,  2.58549685e-01],
       [ 1.85051953e+00,  1.84275283e+00,  1.84330997e+00, ...,
        -1.41046064e-01, -2.41457670e-01,  2.00581253e-01],
       [ 1.85085160e+00,  1.84704429e+00,  1.84680020e+00, ...,
        -1.50494387e-01, -1.80683887e-01,  1.90772720e-01],
       ...,
       [ 1.80298833e+00,  1.79302717e+00,  1.77876232e+00, ...,
        -3.27040358e-02,  1.37080363e-03,  2.66093190e-01],
       [ 1.86807381e+00,  1.87065336e+00,  1.87517253e+00, ...,
        -9.64794732e-02, -9.70021194e-02,  2.21373468e-01],
       [ 1.82285808e+00,  1.82588249e+00,  1.83112749e+00, ...,
         9.72847443e-02,  1.19765931e-01,  5.13567114e-01]])

In [93]:
Data_BDfi=Data_BLD.reshape(-1,1)

In [94]:
Data_BLL = np.load('L_Tyrosine_Baseline.npy')

In [95]:
Data_BLL

array([[-0.02979187, -0.03982631, -0.03659069, ..., -0.17454081,
        -0.20018878,  0.19632693],
       [ 1.78539718,  1.78091283,  1.77849474, ..., -0.12780629,
        -0.24310236,  0.11312423],
       [ 1.79288437,  1.78506897,  1.78234893, ..., -0.1481106 ,
        -0.18996392,  0.17673934],
       ...,
       [ 1.71897101,  1.71498182,  1.70908258, ..., -0.11593349,
        -0.11488929,  0.22938846],
       [ 1.90538064,  1.90024813,  1.88918182, ..., -0.09497677,
        -0.06490326,  0.29483534],
       [ 1.97329994,  1.96942143,  1.95181071, ..., -0.02220776,
         0.00860424,  0.37960623]])

In [96]:
Data_BLfi = Data_BLL.reshape(-1,1)

In [97]:
print(Data_BDfi.shape,Data_BLfi.shape)

(192328, 1) (200618, 1)


In [98]:
X_arrall=np.concatenate((Data_BDfi,Data_BLfi))

In [99]:
X_arrall.shape

(392946, 1)

In [100]:
from sklearn import preprocessing
from keras.utils import to_categorical
y = np.zeros((X_arrall.shape[0],1))
for i in range(0,196473,1):
    if(0<=i<=98236):
        y[i]=0
    elif(98237<=i<=196472):
        y[i]=1
encoder = preprocessing.LabelEncoder()
encoder.fit(y)
encoder_Y = encoder.transform(y)
Y_all1 = to_categorical(encoder_Y)

In [12]:
y2 = []
for i in range(0,196473,1):
    y2.append(0)
    y2.append(1)

In [13]:
y_final = np.array(y2)

In [14]:
y_final.shape

(392946,)

In [15]:
y_arrfinal=y_final.reshape(-1,1)

In [16]:
y_arrfinal

array([[0],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [101]:
print(X_arrall.shape,Y_all1.shape)

(392946, 1) (392946, 2)


In [103]:
X_trainB, X_testB, y_trainB, y_testB = train_test_split(X_arrall, Y_all1, test_size = 0.2, random_state = 42)

In [104]:
print(X_trainB.shape,X_testB.shape,y_trainB.shape,y_testB.shape)

(314356, 1) (78590, 1) (314356, 2) (78590, 2)


In [19]:
model_Logistic2 = LogisticRegression()
model_KN2 = KNeighborsClassifier()
model_Tree2 = DecisionTreeClassifier()
model_SVC2 = SVC()
model_GN2 = GaussianNB()
model_Random2 = RandomForestClassifier()
model_SGD2 = SGDClassifier()

In [106]:
model_KN2 = KNeighborsClassifier()
model_Tree2 = DecisionTreeClassifier()
model_Random2 = RandomForestClassifier()
model_KN2.fit(X_trainB,y_trainB)
model_Tree2.fit(X_trainB,y_trainB)
model_Random2.fit(X_trainB,y_trainB)
y_pred_KN2 = model_KN2.predict(X_testB)
y_pred_Tree2 = model_Tree2.predict(X_testB)
y_pred_Random2 =model_Random2.predict(X_testB)
accuracyKN2 =accuracy_score(y_testB,y_pred_KN2)
accuracyTree2 = accuracy_score(y_testB,y_pred_Tree2)
accuracyRandom2 = accuracy_score(y_testB,y_pred_Random2)
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN2))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree2))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom2))

accuracy_KNeighborsClassifier : 70.17%
accuracy_DecisionTreeClassifier : 61.85%
accuracy_RandomForestClassifier :  63.41%


In [20]:
model_Logistic2.fit(X_trainB,y_trainB)
model_KN2.fit(X_trainB,y_trainB)
model_Tree2.fit(X_trainB,y_trainB)
model_SVC2.fit(X_trainB,y_trainB)
model_GN2.fit(X_trainB,y_trainB)
model_Random2.fit(X_trainB,y_trainB)
model_SGD2.fit(X_trainB,y_trainB)
accuracyKN2 =accuracy_score(y_testB,y_pred_KN2)
accuracyTree2 = accuracy_score(y_testB,y_pred_Tree2)
accuracyRandom2 = accuracy_score(y_testB,y_pred_Random2)

SGDClassifier()

In [21]:
y_pred_Logistic2 = model_Logistic2.predict(X_testB)
y_pred_KN2 = model_KN2.predict(X_testB)
y_pred_Tree2 = model_Tree2.predict(X_testB)
y_pred_SVC2 = model_SVC2.predict(X_testB)
y_pred_GN2 =model_GN2.predict(X_testB)
y_pred_Random2 =model_Random2.predict(X_testB)
y_pred_SGD2 = model_SGD2.predict(X_testB)

In [22]:
from sklearn.metrics import mean_squared_error,r2_score
## MSE
MSE_Logistic2 = mean_squared_error(y_testB,y_pred_Logistic2)
MSE_KN2 = mean_squared_error(y_testB,y_pred_KN2)
MSE_Tree2 = mean_squared_error(y_testB,y_pred_Tree2)
MSE_SVC2 = mean_squared_error(y_testB,y_pred_SVC2)
MSE_GN2 = mean_squared_error(y_testB,y_pred_GN2)
MSE_Random2 = mean_squared_error(y_testB,y_pred_Random2)
MSE_SGD2 = mean_squared_error(y_testB,y_pred_SGD2)

#R-Square
R2_Logistic2 = r2_score(y_testB,y_pred_Logistic2)
R2_KN2 = r2_score(y_testB,y_pred_KN2)
R2_Tree2 = r2_score(y_testB,y_pred_Tree2)
R2_SVC2 = r2_score(y_testB,y_pred_SVC2)
R2_GN2 = r2_score(y_testB,y_pred_GN2)
R2_Random2 = r2_score(y_testB,y_pred_Random2)
R2_SGD2 = r2_score(y_testB,y_pred_SGD2)

In [96]:
print('MSE_Logistic :',MSE_Logistic2)
print('MSE_KNeighborsClassifier :',MSE_KN2)
print('MSE_DecisionTreeClassifier :',MSE_Tree2)
print('MSE_SVC :',MSE_SVC2)
print('MSE_RandomForestClassifier : ',MSE_Random2)
print('MSE_GaussianNB :',MSE_GN2)
print('MSE_SGDClassifier :',MSE_SGD2)

MSE_Logistic : 0.5124110671936759
MSE_KNeighborsClassifier : 0.5017391304347826
MSE_DecisionTreeClassifier : 0.5045059288537549
MSE_SVC : 0.5102766798418973
MSE_RandomForestClassifier :  0.5048221343873518
MSE_GaussianNB : 0.5093280632411067
MSE_SGDClassifier : 0.49810276679841897


In [23]:
print('MSE_Logistic :',MSE_Logistic2)
print('MSE_KNeighborsClassifier :',MSE_KN2)
print('MSE_DecisionTreeClassifier :',MSE_Tree2)
print('MSE_SVC :',MSE_SVC2)
print('MSE_RandomForestClassifier : ',MSE_Random2)
print('MSE_GaussianNB :',MSE_GN2)
print('MSE_SGDClassifier :',MSE_SGD2)

MSE_Logistic : 0.5014505662298002
MSE_KNeighborsClassifier : 0.4991729227637104
MSE_DecisionTreeClassifier : 0.4977096322687365
MSE_SVC : 0.5044025957500954
MSE_RandomForestClassifier :  0.4970352462145311
MSE_GaussianNB : 0.4964753785468889
MSE_SGDClassifier : 0.5022776434660898


In [24]:
print('R2_Logistic : ',R2_Logistic2)
print('R2_KNeighborsClassifier :',R2_KN2)
print('R2_DecisionTreeClassifier :',R2_Tree2)
print('R2_SVC : ',R2_SVC2)
print('R2_RandomForestClassifier : ',R2_Random2)
print('R2_GaussianNB : ',R2_GN2)
print('R2_SGDClassifier :',R2_SGD2)

R2_Logistic :  -1.0058191470355533
R2_KNeighborsClassifier : -0.99670849649077
R2_DecisionTreeClassifier : -0.9908552852469148
R2_SVC :  -1.0176273645014176
R2_RandomForestClassifier :  -0.9881577183258339
R2_GaussianNB :  -0.9859182288064456
R2_SGDClassifier : -1.0091274838255586


In [14]:
from sklearn.metrics import accuracy_score

In [26]:
accuracyLG2 = accuracy_score(y_testB,y_pred_Logistic2)
accuracyKN2 =accuracy_score(y_testB,y_pred_KN2)
accuracyTree2 = accuracy_score(y_testB,y_pred_Tree2)
accuracySVC2 = accuracy_score(y_testB,y_pred_SVC2)
accuracyGN2 = accuracy_score(y_testB,y_pred_GN2)
accuracyRandom2 = accuracy_score(y_testB,y_pred_Random2)
accuracySGD2 = accuracy_score(y_testB,y_pred_SGD2)

In [27]:
print('accuracy_Logistic :',"{:.2%}".format(accuracyLG2))
print('accuracy_KNeighborsClassifier :',"{:.2%}".format(accuracyKN2))
print('accuracy_DecisionTreeClassifier :',"{:.2%}".format(accuracyTree2))
print('accuracy_SVC :',"{:.2%}".format(accuracySVC2))
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyGN2))
print('accuracy_GaussianNB :',"{:.2%}".format(accuracyRandom2))
print('accuracy_SGDClassifier : ',"{:.2%}".format(accuracySGD2))

accuracy_Logistic : 49.85%
accuracy_KNeighborsClassifier : 50.08%
accuracy_DecisionTreeClassifier : 50.23%
accuracy_SVC : 49.56%
accuracy_RandomForestClassifier :  50.35%
accuracy_GaussianNB : 50.30%
accuracy_SGDClassifier :  49.77%


### RandomForest

In [78]:
Data_BLD = np.load('D_Tyrosine_Baseline.npy')
Data_BLL = np.load('L_Tyrosine_Baseline.npy')

In [79]:
Data_BDfi=Data_BLD.reshape(-1,1)
Data_BLfi = Data_BLL.reshape(-1,1)

In [80]:
X_arrall=np.concatenate((Data_BDfi,Data_BLfi))

In [5]:
y2 = []
for i in range(0,196473,1):
    y2.append(0)
    y2.append(1)

In [6]:
y_final = np.array(y2)

In [81]:
from sklearn import preprocessing
from keras.utils import to_categorical
y = np.zeros((X_arrall.shape[0],1))
for i in range(0,196473,1):
    if(0<=i<=98236):
        y[i]=0
    elif(98237<=i<=196472):
        y[i]=1
encoder = preprocessing.LabelEncoder()
encoder.fit(y)
encoder_Y = encoder.transform(y)
Y_all = to_categorical(encoder_Y)

In [82]:
print(X_arrall.shape,Y_all.shape)

(392946, 1) (392946, 2)


In [83]:
X_train, X_test, y_train, y_test = train_test_split(X_arrall,Y_all, test_size = 0.2, random_state = 42)

In [87]:
from sklearn.metrics import accuracy_score
model_Random2 = RandomForestClassifier(n_estimators=200,max_depth=5,min_samples_leaf=500,min_samples_split=500)
model_Random2.fit(X_train,y_train)
y_pred_Random2 =model_Random2.predict(X_test)
accuracyRandom2 = accuracy_score(y_test,y_pred_Random2)
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom2))

accuracy_RandomForestClassifier :  75.08%


In [88]:
from sklearn.metrics import classification_report
target_names = ['class_D','class_L']
print(classification_report(y_test, y_pred_Random2, target_names=target_names))

              precision    recall  f1-score   support

     class_D       0.75      1.00      0.86     59008
     class_L       0.00      0.00      0.00     19582

   micro avg       0.75      0.75      0.75     78590
   macro avg       0.38      0.50      0.43     78590
weighted avg       0.56      0.75      0.64     78590
 samples avg       0.75      0.75      0.75     78590



In [15]:
model_Random2 = RandomForestClassifier(n_estimators=200,max_features='auto',min_samples_leaf=2,
                                       min_samples_split=5,max_depth=10,class_weight='balanced', 
                                        verbose=1, random_state=42)
model_Random2.fit(X_train,y_train)
y_pred_Random2 =model_Random2.predict(X_test)
accuracyRandom2 = accuracy_score(y_test,y_pred_Random2)
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom2))

accuracy_RandomForestClassifier :  63.42%


In [88]:
from sklearn.metrics import accuracy_score
model_Random2 = RandomForestClassifier(n_estimators=150,max_depth=10,min_samples_leaf=2,min_samples_split=10)
model_Random2.fit(X_train,y_train)
y_pred_Random2 =model_Random2.predict(X_test)
accuracyRandom2 = accuracy_score(y_test,y_pred_Random2)
print('accuracy_RandomForestClassifier : ',"{:.2%}".format(accuracyRandom2))

accuracy_RandomForestClassifier :  75.07%


In [8]:
rf = RandomForestClassifier(random_state = 42)
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [10]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]

max_features = ['auto', 'sqrt','log2']

max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)

min_samples_split = [2, 5, 10,20,25]

min_samples_leaf = [1, 2, 4,6,8,10]

bootstrap = [True, False]

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt', 'log2'],
 'min_samples_leaf': [1, 2, 4, 6, 8, 10],
 'min_samples_split': [2, 5, 10, 20, 25],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [ ]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train, y_train)
rf_random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'bootstrap': [True],
    'n_estimators' : [10,20,30,40,50,60,70,80,90,100,200,500,800],
    'criterion' : ['gini','entropy'],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000],
    'max_features' : ['auto','sqrt','log2'],
    'class_weight' : ['balanced','balanced_subsample']
}

rf = RandomForestClassifier()

grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_train,y_train)
grid_search.best_params_

Fitting 3 folds for each of 1728 candidates, totalling 5184 fits


### KNeighborsClassifier

In [89]:
from sklearn.metrics import accuracy_score
model_KN2 = KNeighborsClassifier()
model_KN2.fit(X_train,y_train)
y_pred_KN2 =model_KN2.predict(X_test)
accuracyKN2 = accuracy_score(y_test,y_pred_KN2)
print('accuracy_KN : ',"{:.2%}".format(accuracyKN2))

accuracy_KN :  70.17%


In [90]:
from sklearn.metrics import classification_report
target_names = ['class_D','class_L']
print(classification_report(y_test, y_pred_KN2, target_names=target_names))

              precision    recall  f1-score   support

     class_D       0.75      0.89      0.82     59008
     class_L       0.28      0.12      0.17     19582

   micro avg       0.70      0.70      0.70     78590
   macro avg       0.52      0.51      0.49     78590
weighted avg       0.64      0.70      0.66     78590
 samples avg       0.70      0.70      0.70     78590



### DiscisionTree

In [31]:
from sklearn.metrics import accuracy_score
model_Tree = DecisionTreeClassifier(max_depth=5,min_samples_leaf=3000)
model_Tree.fit(X_train,y_train)
y_pred_Tree =model_Tree.predict(X_test)
accuracyTree = accuracy_score(y_test,y_pred_Tree)
print('accuracy_Tree : ',"{:.2%}".format(accuracyTree))

accuracy_Tree :  75.08%


In [35]:
from sklearn.metrics import classification_report
target_names = ['class_D','class_L']
print(classification_report(y_test, y_pred_Tree, target_names=target_names))

              precision    recall  f1-score   support

     class_D       0.75      1.00      0.86     59008
     class_L       0.00      0.00      0.00     19582

   micro avg       0.75      0.75      0.75     78590
   macro avg       0.38      0.50      0.43     78590
weighted avg       0.56      0.75      0.64     78590
 samples avg       0.75      0.75      0.75     78590

